version: 0.2

phases:
  install:
    commands:
      - echo install started on `date`
      - yum update -y 2>&1 >/dev/null
      - yum install -y perl-Digest-MD5
      - wget -q0- http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz | tar xvz 2>&1 >/dev/null
      - echo "I" | ./install-tl*/install-tl -no-gui -repository http://mirror.ctan.org/systems/texlive/tlnet/
      - /usr/local/texlive/????/bin/*/tlmgr path add
      - pip3 install -U sphinx
  pre_build:
    commands:
      - echo pre_build started on `date`
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      
artifacts:
  files:
    - '**/*'
  base-directory: $CODEBUILD_SRC_DIR
  
cach:
  paths:
   - 'usr/local/texlive/2020/**/*'